language: node_js
node_js: stable
branches:
  only:
  - master
install:
- npm install
script:
- npm test
after_script:
- NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
after_success:
- echo codecov && ./node_modules/.bin/codecov #运行codecov
